tags:
  unspec-ccd-stack: false

postgresql:
  enabled: false

idam-pr:
  enabled: false

xui-webapp:
  enabled: false

camunda-bpm:
  enabled: false

java:
  applicationPort: 4000
  image: 'hmctspublic.azurecr.io/civil/service:latest'
  aadIdentityName: unspec
  keyVaults:
    unspec:
      resourceGroup: unspec
      secrets:
        - unspec-idam-client-secret
        - microservicekey-unspec-service
        - system-update-user-username
        - system-update-user-password
        - AppInsightsInstrumentationKey
        - docmosis-api-key
        - gov-notify-api-key
        - sendgrid-api-key
        - robotics-notification-sender
        - robotics-notification-recipient
        - launch-darkly-sdk-key
